name: main

on:
  push:
    branches:
      - master
      - next
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - next
      - '[0-9]+.[0-9]+'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
         sudo apt-get install shellcheck
         shellcheck --version
      - name: lint
        run: |
         make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          git clone https://github.com/bats-core/bats-core.git /tmp/bats
          sudo /tmp/bats/install.sh /usr/local
          bats --version
      - name: test
        run: |
         make test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution:
          - admin
          - adminpresentation
          - allinone
          - build
          - ingest
          - presentation
          - worker
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
          docker info

      - name: build container image
        run: |
          make "build-${{ matrix.distribution }}"

      - uses: docker/login-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      - name: push container image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push "quay.io/opencast/${{ matrix.distribution }}:${{ matrix.opencast_version }}"
